---
title: "Work"
author: "Xin Guan"
date: "04/10/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Install packages

```{r}
library(readr) #For read_csv
library(dplyr)
library("fs") # for cross-platform directories (path_wd)
library("knitr") # For kable 
library("gplots")
```

# Import Data

```{r}
data <- read_csv("~/Desktop/DST/DST_Assessment_0/Report/01-Data.csv")
data.f= as.data.frame(data)
#read_csv imported data as tbl which is a subclass of data frame, however it behaves differentlt so I convert it to data.frame format.
```
```{r}
head(data.f)
```
```{r}
summary(data.f)
```
```{r}
barplot((sort(table(data.f[,"Embarked"]))),names.arg=c("Cherbourg","Queenstown","Southampton"))
```
```{r}
barplot((table(data.f[,"Sex"])),names.arg=c("female","male"))
```




```{r}
data.f<-data.f[-which(is.na(data.f$Embarked)),]
#Remove the rows with NA for Embarked variable.
```

```{r}
labs=unique(as.character(data.f[,"Embarked"]))
names(labs)=labs

list=lapply(labs,function(x){
  data.f[data.f[,"Embarked"]==x,1:11]
})
#Separate data in to three sub-data by the port of embark.
```

```{r}
data.f %>% count(Embarked)
# Count each numbers of each value in the Embarked variable
```


```{r}
datamean=t(sapply(list,function(x)colMeans(x[,c(3,6,7,8,10)])))
heatmap.2(datamean,trace="none")
```
```{r}
datamean
# We can see that Age mean is not calculated since we have missing data.
```
```{r}
#Plot heatmap withou Age variable
datamean2=t(sapply(list,function(x)colMeans(x[,c(3,7,8,10)])))
heatmap.2(datamean2,trace="none",margins=c(7,3))
```

```{r}
data.f %>% count(Sex)
```

```{r}
genders=unique(as.character(data.f[,"Sex"]))
names(genders)=genders
genders_data=lapply(genders,function(x){
  data.f[data.f[,"Sex"]==x,]
})
male_data<-genders_data[1]
female_data<-genders_data[2]
female_data= as.data.frame(female_data)
male_data= as.data.frame(male_data)
# Separate data into two sub data by genders
```

```{r}
fe_sur_rate <- sum(female_data$female.Survived)/dim(female_data)[1]

male_sur_rate <- sum(male_data$male.Survived)/dim(male_data)[1]
```

```{r}
fe_sur_rate
male_sur_rate
```















